USE 503190_jorge_pineiro;

-- Trigger AFTER que agrega la fecha de creacion luego de que se carga un registro.
DROP TRIGGER IF EXISTS TR_FECHA_CREACION;
DELIMITER $$
CREATE TRIGGER TR_FECHA_CREACION
AFTER INSERT ON JUEGOS
FOR EACH ROW
BEGIN
    UPDATE JUEGOS SET FECHA_CREACION = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END $$
DELIMITER ;
-- Verificamos el trigger
SELECT * FROM JUEGOS;

-- Trigger BEFORE que nos muestra la ultima fecha de modificacion que tuvo el registro. Por defecto el valor va a ser NULL
DROP TRIGGER IF EXISTS TR_ULTIMA_MODIFICACION;
DELIMITER $$
CREATE TRIGGER TR_ULTIMA_MODIFICACION
BEFORE UPDATE ON JUEGOS
FOR EACH ROW
BEGIN
    SET NEW.FECHA_ULTIMA_MODIFICACION = CURRENT_TIMESTAMP;
END $$
DELIMITER ;

UPDATE JUEGOS
SET TITULO = 'The Witcher 3 - Modificado'
WHERE TITULO = 'The Witcher 3';

SELECT * FROM JUEGOS;